import { defineConfig } from 'orval'

export default defineConfig({
  music: {
    input: {
      target: './music.openapi.json',
    },
    output: {
      mode: 'split',
      target: './src/api/generated',
      schemas: './src/types/generated',
      client: 'axios',
      httpClient: 'axios',
      clean: true,
      prettier: true,
      override: {
        mutator: {
          path: './src/api/mutator/custom-instance.ts',
          name: 'customInstance',
        },
        operations: {
          // 为音乐相关的操作添加标签
          'get/comment/get_hot_comments': {
            operationName: 'getHotComments',
            tags: ['Comments'],
          },
          'get/search/complete': {
            operationName: 'searchComplete', 
            tags: ['Search'],
          },
        },
        header: (info) => [
          '/**',
          ` * Generated by orval v${info.version} 🍺`,
          ' * Do not edit manually.',
          ` * ${info.title}`,
          ` * ${info.description}`,
          ' */',
        ],
        query: {
          useQuery: true,
          useInfiniteQuery: true,
          options: {
            staleTime: 10000,
          },
        },
      },
    },
    hooks: {
      afterAllFilesWrite: 'prettier --write',
    },
  },
})
